CREATE DATABASE cadastro;
USE cadastro;
CREATE TABLE clientes(id int AUTO_INCREMENT PRIMARY KEY NOT NULL,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
senha VARCHAR(100) NOT NULL,
cep VARCHAR(12) NOT NULL,
rua VARCHAR(100) NOT NULL,
numero INT NOT NULL,
bairro VARCHAR(30) NOT NULL,
complemento VARCHAR(20) NOT NULL,
cidade VARCHAR(100) NOT NULL,
estado VARCHAR(3) NOT NULL);